### ISSUE TITLE
Bianco and Riot

### ISSUE THREAD

**Issue by anonimusprogramus** [biancojs/bianco#1]
Hi @GianlucaGuarini 

Is Biancojs going to be used in Riotjs's rewrite plan?

Thanks

**Comment by GianlucaGuarini** [comment]
Hi @anonimusprogramus, Bianco.js and Riot.js are 2 different projects.
I use Bianco.js to have a modern functional DOM API for all the things that can't be handled via Riot.js or any other framework like for example reading the viewport data via [bianco.viewport](https://github.com/biancojs/viewport) or for demos like [this](https://codepen.io/GianlucaGuarini/pen/WgEzpr).
Riot.js on the other hand could use [bianco.events](https://github.com/biancojs/events) and [bianco.query](https://github.com/biancojs/query) as internal helpers but I would like to handle the riot core directly in riot without mixing the 2 projects to avoid unnecessary dependencies. Bianco.js is my official DOM helpers library (a kind of modern and modular jQuery), Riot.js is a mini components library that is meant to be used for complex web applications I think that **combining both by default** is not a winning strategy but they could be required and installed on demand if needed playing nicely together. Thanks for your question and have fun using both!
